### ISSUE TITLE
Multitude of bugs making the app unusable for me

### ISSUE THREAD

**Issue by OldaysStudios** [Shock9616/Phoenix#20] opened 2023-05-20 15:51 UTC
I'll just list them for simplicity, I would love to be able to use the app but these bugs make it too annoying.

1. If the app icon clicked in dock, the app is focused, but not brought to the front.
2. When the app is hidden with the red traffic light button and brought back up, the window size resets to be smaller.
3. None of the icon or headers work, no matter how many times they are edited.
4. Deleting Steam games from the list doesn't work properly, loading the app back up brings them up again but not always, I just want a selective list without auto-adding.
5. Having two apps with the same name freaks the list out.
6. The info on the right side with reviews etc. is misaligned.
7. When the app is hidden, sometimes it will not refocus at all, so it just becomes invisible.
8. Making simple edits resets some of the custom options such as date, developer, publisher etc.

**Comment by Shock9616** [comment] 2023-05-24 01:36
Thank you for letting me know about all these bugs!

1/7/8: I am not able to reproduce these issues, are you able to get a screen recording of them?

2: The red traffic light button is the close window button, it doesn't just hide the app. I do plan to make the app remember its window size eventually, but there are still some much more pressing issues to deal with

3: This is a known issue with the 3rd release of the app. I haven't been able to figure out what's going on with this issue, but that's one of my top priorities to fix right now. It is quite annoying so I recommend sticking with the 2nd release until this gets fixed.

4: This is working "as intended" for now. Currently I haven't implemented a way to turn off auto-detection of Steam games since I wanted to focus more on getting the feature working properly. When I get around to making a settings window I will add this ability, but for now I figured that most people would want their Steam library auto-imported so I've left that for later.

5: I didn't know about this one, I never tested this as it never occurred to me that anyone would have 2 apps with the same name. I believe that this is because currently the selection is based on the name alone, so I'll have to find a different way of identifying the selection to fix this issue.

6: I am aware of this one, currently the columns are basically just 2 text boxes sat next to each other which is hard to align properly. Once I get this data to start updating, I'll probably move it into a table or something so that it aligns properly.

I have been quite busy lately so I haven't had much time at all to work on this project, but I really appreciate you letting me know about all these issues for when I do get back to working on it, I'll definitely make sure that all of this is on the todo list 🙂

**Comment by jxhug** [comment] 2023-06-10 19:50
Issue 2 is default macOS behavior. You'll find that if you close the app using the red traffic light button it'll resize, but if you quit the app and reopen it'll remember the window size. I will tackle the other issues soon.

**Comment by jxhug** [comment] 2023-06-11 05:37
Issue 1 was probably some weird macOS behavior. Like Shock9616, I wasn't able to replicate it. 

I've just fixed Issue 3 and am waiting for the PR to be approved. There should be a build soon after with the changes made. 

I will be working on Issue 6 next. I'm interested in 4 & 5 but don't feel like touching the app's backend at the moment.

**Comment by Shock9616** [comment] 2023-06-12 23:43
@OldaysStudios The [latest release](https://github.com/Shock9616/Phoenix/releases/tag/v0.0.4-alpha) fixes issue 3! I will soon get working on adding a basic settings window, and will be sure to include the ability to toggle steam game detection. When this feature gets added I will make it be off by default as well. I hope that you'll be able to enjoy using Phoenix soon!

**Comment by Shock9616** [comment] 2023-06-15 07:16
I have added a new settings window in my last commit that includes a toggle for game detection, so number 4 will be fixed in the next release.

**Comment by jxhug** [comment] 2023-06-22 22:07
will be completely fixed by the next release which is expected in a few days

**Closed** 2023-06-22 22:06 UTC
Labels: bug
